import { Role } from "@/types/role";
import { User } from "@/types/user";
import { mockOrganizations } from "./mockOrganizations";

export const mockUsers: User[] = [
    {
        id: "1",
        name: "John Doe",
        email: "john.doe@example.com",
        password: "password123",
        createdAt: "2023-01-01T00:00:00.000Z",
        updatedAt: "2023-01-01T00:00:00.000Z",
        role: Role.INSTRUCTOR,
        avatar: "https://example.com/avatar.jpg",
        organizations_admin: [],
        organizations_instructor: [mockOrganizations[0]],
    },
    {
        id: "2",
        name: "Jane Smith",
        email: "jane.smith@example.com",
        password: "password123",
        createdAt: "2023-01-02T00:00:00.000Z",
        updatedAt: "2023-01-02T00:00:00.000Z",
        role: Role.INSTRUCTOR,
        avatar: "https://example.com/avatar.jpg",
        organizations_admin: [],
        organizations_instructor: [mockOrganizations[0]],
    },
    {
        id: "3",
        name: "Michael Johnson",
        email: "michael.johnson@example.com",
        password: "password123",
        createdAt: "2023-01-03T00:00:00.000Z",
        updatedAt: "2023-01-03T00:00:00.000Z",
        role: Role.USER,
        avatar: "https://example.com/avatar3.jpg",
        organizations_admin: [],
        organizations_instructor: [],
    },
    {
        id: "4",
        name: "Emily Davis",
        email: "emily.davis@example.com",
        password: "password123",
        createdAt: "2023-01-04T00:00:00.000Z",
        updatedAt: "2023-01-04T00:00:00.000Z",
        role: Role.ADMIN,
        avatar: "https://example.com/avatar4.jpg",
        organizations_admin: [mockOrganizations[1]],
        organizations_instructor: [],
    },
    {
        id: "5",
        name: "David Wilson",
        email: "david.wilson@example.com",
        password: "password123",
        createdAt: "2023-01-05T00:00:00.000Z",
        updatedAt: "2023-01-05T00:00:00.000Z",
        role: Role.INSTRUCTOR,
        avatar: "https://example.com/avatar5.jpg",
        organizations_admin: [],
        organizations_instructor: [mockOrganizations[1]],
    },
    {
        id: "6",
        name: "Sarah Brown",
        email: "sarah.brown@example.com",
        password: "password123",
        createdAt: "2023-01-06T00:00:00.000Z",
        updatedAt: "2023-01-06T00:00:00.000Z",
        role: Role.USER,
        avatar: "https://example.com/avatar6.jpg",
        organizations_admin: [],
        organizations_instructor: [],
    },
    {
        id: "7",
        name: "Robert Taylor",
        email: "test@example.com",
        password: "password123",
        createdAt: "2023-01-07T00:00:00.000Z",
        updatedAt: "2023-01-07T00:00:00.000Z",
        role: Role.SUPER_ADMIN,
        avatar: "https://example.com/avatar7.jpg",
        organizations_admin: [mockOrganizations[0], mockOrganizations[1]],
        organizations_instructor: [],
    },
    {
        id: "8",
        name: "Jennifer Miller",
        email: "jennifer.miller@example.com",
        password: "password123",
        createdAt: "2023-01-08T00:00:00.000Z",
        updatedAt: "2023-01-08T00:00:00.000Z",
        role: Role.INSTRUCTOR,
        avatar: "https://example.com/avatar8.jpg",
        organizations_admin: [],
        organizations_instructor: [mockOrganizations[2]],
    },
    {
        id: "9",
        name: "Thomas Anderson",
        email: "thomas.anderson@example.com",
        password: "password123",
        createdAt: "2023-01-09T00:00:00.000Z",
        updatedAt: "2023-01-09T00:00:00.000Z",
        role: Role.USER,
        avatar: "https://example.com/avatar9.jpg",
        organizations_admin: [],
        organizations_instructor: [],
    },
    {
        id: "10",
        name: "Lisa Garcia",
        email: "lisa.garcia@example.com",
        password: "password123",
        createdAt: "2023-01-10T00:00:00.000Z",
        updatedAt: "2023-01-10T00:00:00.000Z",
        role: Role.ADMIN,
        avatar: "https://example.com/avatar10.jpg",
        organizations_admin: [mockOrganizations[2]],
        organizations_instructor: [],
    },
];