import { RegisteredExam } from "@/types/registered-exam";
import { mockUsers } from "./mockUsers";
import { mockAdditionalExams, mockIELTSExams } from "./mockIeltsExam";
import { Currency } from "@/types/currency";

export const registeredExams: RegisteredExam[] = [
  {
    id: "reg-1",
    user: mockUsers[6],
    exam: mockIELTSExams[0],
    registered_at: "2025-07-01T10:00:00Z",
    payment_status: "paid",
    paid_amount: 100,
    currency: Currency.BDT,
    status: "registered",
    speaking_time: {
      date: "2025-08-01",
      start: "10:00",
      end: "10:30",
      instructor: {
        id: "inst-1",
        name: "Instructor A",
      },
    },
  },
  {
    id: "reg-2",
    user: mockUsers[6],
    exam: mockIELTSExams[1],
    registered_at: "2025-07-02T11:00:00Z",
    payment_status: "paid",
    paid_amount: 0,
    currency: Currency.BDT,
    status: "registered",
  },
  {
    id: "reg-3",
    user: mockUsers[6],
    exam: mockIELTSExams[2],
    registered_at: "2025-07-03T12:00:00Z",
    payment_status: "pending",
    paid_amount: 80,
    currency: Currency.BDT,
    status: "registered",
  },
  {
    id: "reg-4",
    user: mockUsers[6],
    exam: mockIELTSExams[3],
    registered_at: "2025-07-04T13:00:00Z",
    payment_status: "failed",
    paid_amount: 150,
    currency: Currency.BDT,
    status: "cancelled",
  },
  {
    id: "reg-5",
    user: mockUsers[6],
    exam: mockIELTSExams[4],
    registered_at: "2025-07-05T14:00:00Z",
    payment_status: "refunded",
    paid_amount: 120,
    currency: Currency.BDT,
    status: "cancelled",
  },
  {
    id: "reg-6",
    user: mockUsers[6],
    exam: mockAdditionalExams[0],
    registered_at: "2025-07-06T15:00:00Z",
    payment_status: "paid",
    paid_amount: 200,
    currency: Currency.BDT,
    status: "registered",
    speaking_time: {
      date: "2025-08-01",
      start: "10:00",
      end: "10:30",
      instructor: {
        id: "inst-1",
        name: "Instructor A",
      },
    },
  },
  {
    id: "reg-7",
    user: mockUsers[6],
    exam: mockAdditionalExams[1],
    registered_at: "2025-07-07T16:00:00Z",
    payment_status: "paid",
    paid_amount: 90,
    currency: Currency.BDT,
    status: "completed",
  },
  {
    id: "reg-8",
    user: mockUsers[6],
    exam: mockAdditionalExams[2],
    registered_at: "2025-07-08T17:00:00Z",
    payment_status: "paid",
    paid_amount: 85,
    currency: Currency.BDT,
    status: "registered",
  },
  {
    id: "reg-9",
    user: mockUsers[6],
    exam: mockAdditionalExams[3],
    registered_at: "2025-07-09T18:00:00Z",
    payment_status: "pending",
    paid_amount: 130,
    currency: Currency.BDT,
    status: "registered",
  },
  {
    id: "reg-10",
    user: mockUsers[6],
    exam: mockAdditionalExams[4],
    registered_at: "2025-07-10T19:00:00Z",
    payment_status: "paid",
    paid_amount: 160,
    currency: Currency.BDT,
    status: "completed",
    speaking_time: {
      date: "2025-08-02",
      start: "11:00",
      end: "11:30",
      instructor: {
        id: "inst-2",
        name: "Instructor B",
      },
    },
  },
];
